# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e91f881d7a3e44b9c705661c7aca9284"
name = "duilo-migration-app"
handle = "duilo-migration-app"
application_url = "https://example.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
